name: Deploy Storybook to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: Build Storybook
        run: sh ./build-storybook.sh

      - name: Push Storybook to deployment repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SECRET_ACCESS_KEY }} # secret ë³€ìˆ˜(í† í°)
        with:
          source-directory: "storybook-output"
          destination-github-username: 78-artilleryman # ê°œì¸ ë ˆí¬ ì£¼ì¸ username
          destination-repository-name: zighang-storybook # Storybook ë°°í¬ìš© ë ˆí¬
          user-email: ${{ secrets.AUTO_EMAIL }} # secret ë³€ìˆ˜(ì´ë©”ì¼)
          commit-message: "ğŸ“š Deploy Storybook: ${{ github.event.commits[0].message }}"
          target-branch: main # Vercelê³¼ ì—°ë™ëœ ë¸Œëœì¹˜

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
